### DISCUSSION TITLE
Use YAML (or TOML) as the EGSnrc input file language

### DISCUSSION THREAD

**Discussion by ftessier** [nrc-cnrc/EGSnrc#659] [Ideas]
What do you think about using the well-known and standardized markup language [YAML](https://yaml.org/) for EGSnrc input files, especially the egs++ `.egsinp` files, instead of EGSnrc's own format (using `:start` and `:stop` tags and nested key-value pairs). The yaml specification is also a key-value pair format, so it is very similar to `.egsinp` format.

There are libraries readily available to parse yaml in all common languages, and **one can write a JSON schema to automatically validate EGSnrc input files.** In fact, the idea to look at yaml again was precipitated by the recent [input validation discussion](https://github.com/nrc-cnrc/EGSnrc/discussions/651#discussion-61908).

I have also considered TOML and JSON, but I don't think those fit the bill. Note that this can be implemented on the side (i.e., leaving the traditional `.egsinp` format available; if in time yaml input gained traction, we could also write a converter of course.

I have been toying with the idea a little, and found the following pros for yaml input:

1. simple, clean with minimal syntactic crud
2. widely recognized standard syntax, with libraries to parse and editor support for syntax highlighting
3. support for JSON schema to specify and validate EGSnrc input (I have started to write a schema)
4. key value pairs, so almost identical to `.egsinp` already (notably, whitespace is allowed in keys)
5. support for scientific notation
6. convenient marker and reference notation to replicate data (any input can be turned in a variable to be reused, see `&pos 0.935` and `*pos` in the example below)
7. can easily clone entries while modifying only some elements (see `<<: *tip` in example below)
8. supports explicit type annotations if needed (e.g., `!!str 2.0`)
9. no need to balance delimiters (except in sequences, which is then a little annoying)
10. any json file is a valid yaml file, so inputs _could_ be written in json.
11. forced indentation :slightly_smiling_face:

Here is what a typical input might look like:

```yaml
### ----------------------------------------------------------------------------
### Simulation
### ----------------------------------------------------------------------------
simulation:
  ncase:      1.e+16
  precision:  1%
  geometry:   chamber
  source:     my_source
  rng:
    seeds: [123, 1250]

### ----------------------------------------------------------------------------
### Geometries
### ----------------------------------------------------------------------------
geometries:

  # the ion chamber spherical tip
  - &tip
    name:       chamber_tip
    class:      egs_spheres
    position:   [&pos 0.931, 0, -10]
    radii:      [0.05, 0.311, 0.356, 0.36, 0.37, 1.0]
    media:
      water:  all
      pmma:   [0, 2]
      air:    [1, 3]

  # the same chamber tip, at a different z-position
  - <<: *tip
    name: chamber_tip_2
    midpoint:   [0, *pos, -23]

  # the cylindrical body of the ion chamber
  - name:       chamber_body
    class:      egs_cones
    type:       EGS_ConeStack
    origin:     [0.985, 0, -10]
    direction:  [-1, 0, 0]

    layers:

      - name:         electrode
        thickness:    2.03
        top radii:    [0.05, 0.311, 0.356]
        bottom radii: [0.05, 0.311, 0.356]
        media:        [pmma, air, pmma]

      - name:         stem
        thickness:    2.0
        top radii:    0.62
        bottom radii: 0.62
        media:        pmma

  # join the chamber tip and body to build chamber
  - name:   chamber
    class:  egs_cdgeometry
    template: cd_planes_for_chamber
    fill region 0: chamber_body
    fill region 1: chamber_tip

### ----------------------------------------------------------------------------
### Sources
### ----------------------------------------------------------------------------
sources:
  - name: my_source
    class: egs_collimated_source
    charge: 0
    source shape:
      type: point
      position: [0, 0, 100]
    target shape:
      class: egs_rectangle
      rectangle: [-5, 0, 5, 5]
    spectrum:
      type: monochromatic
      energy: 6 MeV
```

I am working on a JSON schema to specify the permitted and required EGSnrc input, for validation, and will post it here as soon as I have something decent.

**Comment by rtownson** [comment]
One question is how the performance will compare when the file is very large. Since this only happens once per simulation I imagine it won't be important, but worth checking - I have an egsinp that's 9.2MB, let me know if you want to give it a try.

**Reply by ftessier** [reply]
Good point. Like you I am not too worried about performance, but I would not want to wait for seconds at startup either for MB size input files. On the flip side validation is probably useful for such a large file (though I expect---hope---it is mostly generated from a script!). For some _cons_ regarding YAML: https://www.arp242.net/yaml-config.html.

**Reply by ftessier** [reply]
As mentioned in that article, we ought to stick with StrictYAML if trying the yaml route.

**Reply by ftessier** [reply]
Tried to load a 10 MB yaml file using the python parser. Yikes! Way too slow, I was not patient enough to let it complete. It was 108 seconds for a 5 MB file! The c++ library is perhaps much faster. We _will_ have to think about performance then.

**Reply by crcrewso** [reply]
With the new structure does the 9 MB Egsinp file actually translate to a 9 MB yaml file?

**Reply by ftessier** [reply]
Have not calculated exactly, but give and take, yes, it would be similar.

**Reply by ftessier** [reply]
I tried parsing a large yaml input file with [`yaml_rust`](https://crates.io/crates/yaml-rust), and it can chew through MB of inputs practically instantly. We could check performance in more detail, but I am confident parsing efficiency is not an issue with `libyaml`, `yaml-cpp` or `yaml_rust`.

**Comment by ftessier** [comment]
I like TOML (https://toml.io/) as well, it is simpler and clearer. I will try writing an `.egsinp` in TOML as well, to test this idea. Looking at it again, I found that one can write a JSON schema as well to validate TOML (and a TOML-specific schema will probably arise in the future). While looking at yaml, I found that the variable definition and reuse ability in yaml (points 6 and 7 in list above) sounded great for EGSnrc geometries!

**Comment by ftessier** [comment]
Below is a similar input file example in TOML. I really like the clean and unambiguous structure, however quoting all those strings is driving me nuts! 😄 . Use the following python snip to parse:

```python
# install toml with: pip install toml

import toml

with open("egsinp.toml") as egsinp:
    egsinput = toml.loads(egsinp.read())

str = toml.dumps(egsinput)
print(str)
print(egsinput)
```


```toml
### ----------------------------------------------------------------------------
### Simulation
### ----------------------------------------------------------------------------

[simulation]
ncase       = 1000
precision   = 0.01
geometry    = "chamber"
source      = "my_source"
[simulation.rng]
    type    = "xoshiro"
    seeds   = [123, 1250]


### ----------------------------------------------------------------------------
### Geometries
### ----------------------------------------------------------------------------

# chamber tip
[[geometry]]
name        = "chamber_tip"
type        = "egs_spheres"
position    = [0.931, 0.0, -10.0]
radii       = [0.05, 0.311, 0.356, 0.36, 0.37, 1.0]
[geometry.media]
    water = "all"
    pmma  = [0, 2]
    air   = [1, 3]

# chamber body
[[geometry]]
name        = "chamber_body"
type        = "EGS_ConeStack"
origin      = [0.985, 0.01, -10.0]
direction   = [-1, 0, 0]

[[geometry.layer]]
    name        = "electrode"
    thickness   = 2.03
    top         = [0.05, 0.311, 0.356]
    bottom      = [0.05, 0.311, 0.356]
    media       = ["pmma", "air", "pmma"]

[[geometry.layer]]
    name        = "stem"
    thickness   = 2.0
    top         = 0.61
    bottom      = 0.61
    media       = "pmma"

# combine chamber tip and body
[[geometry]]
name        = "chamber"
type        = "egs_cdgeometry"
template    = "cd_planes_for_chamber"
[geometry.regions]
    0 = "chamber_body"
    1 = "chamber_tip"


### ----------------------------------------------------------------------------
### Sources
### ----------------------------------------------------------------------------

[[source]]
name                    = "my_source"
type                    = "egs_collimated_source"
particle                = "photon"
spectrum.type           = "monochromatic"
spectrum.energy         = 6
shapes.source.type      = "point"
shapes.source.position  = [0, 0, 100]
shapes.target.type      = "rectangle"
shapes.target.rectangle = [-5, 0, 5, 5]
```

Note that the pythom toml library at this point only support the `0.5.0` toml spec, which does not allows mixed type arrays. However mixed type arrays are in the `1.0.0-rc.3` toml spec.

**Reply by ftessier** [reply]
Playing around with this a bit more, the constant quoting is really annoying, and the nested structures is a bit opaque when looking at the input for more complicated case (nesting is not really visible, unless you add non-required indentation), so I don't think TOML is best for `.egsinp` files. I am back to YAML. Or perhaps StrictYaml, but then we loose references, which would be useful in egsinp geometries. Still pondering.

**Reply by mchamberland** [reply]
Having not really thought or looked about it much, but having recently looked at YAML vs TOML for another project, my vote goes to YAML.

**Reply by ftessier** [reply]
Thanks @mchamberland! Having not used much of either (and then again only as a user in conf files etc.), your comment proves useful!

**Comment by ftessier** [comment]
Here is a better layout, where the `name` properties are turned into the dictionary keys, which makes for a more readable input:

```yaml
geometries:

  # the ion chamber spherical tip
  chamber_tip:
    class:    egs_spheres
    midpoint: [&pos 0.935, 0, -10]
    radii:    [0.05, 0.305, 0.355]
    media:
      water:  all
      air:    [1, 2, 3]
      pmma:   [4, 5]

  # the cylindrical body of the ion chamber
  chamber_body:
    class:     egs_conestack
    origin:    [*pos, 0, -10]
    direction: [-1, 0, 0]
    layers:
      - electrode:
          thickness:    2.03
          top radii:    [0.05, 0.305, 0.355]
          bottom radii: [0.05, 0.305, 0.355]
          media:        [&medium pmma, air, *medium]
      - stem:
          thickness:    2.0
          top radii:    0.61
          bottom radii: 0.61
          media:        *medium

  # join the chamber tip and body to build chamber
  chamber:
    class: egs_cdgeometry
    base geometry: cd_planes_for_chamber
    fill region 0: chamber_body
    fill region 1: chamber_tip
    new indexing style: true
```

which parses to the following JSON:

```json
{
    "geometries": {
        "chamber_tip": {
            "class": "egs_spheres",
            "midpoint": [
                0.935,
                0,
                -10
            ],
            "radii": [
                0.05,
                0.305,
                0.355
            ],
            "media": {
                "water": "all",
                "air": [
                    1,
                    2,
                    3
                ],
                "pmma": [
                    4,
                    5
                ]
            }
        },
        "chamber_body": {
            "class": "egs_conestack",
            "origin": [
                0.935,
                0,
                -10
            ],
            "direction": [
                -1,
                0,
                0
            ],
            "layers": [
                {
                    "electrode": {
                        "thickness": 2.03,
                        "top radii": [
                            0.05,
                            0.305,
                            0.355
                        ],
                        "bottom radii": [
                            0.05,
                            0.305,
                            0.355
                        ],
                        "media": [
                            "pmma",
                            "air",
                            "pmma"
                        ]
                    }
                },
                {
                    "stem": {
                        "thickness": 2.0,
                        "top radii": 0.61,
                        "bottom radii": 0.61,
                        "media": "pmma"
                    }
                }
            ]
        },
        "chamber": {
            "class": "egs_cdgeometry",
            "base geometry": "cd_planes_for_chamber",
            "fill region 0": "chamber_body",
            "fill region 1": "chamber_tip",
            "new indexing style": true
        }
    }
}
```

I used the following python snippet to convert yaml to json:

```python
import sys
import yaml
import json

with open(sys.argv[1]) as f:
    yaml_content = yaml.safe_load(f)

print(json.dumps(yaml_content, indent=4))
```

**Comment by ftessier** [comment]
Having a json representation would allow validation through a json schema. A json schema also allows for _automatically_ generating a validating web interface to egsinp content. Strict json as an input syntax is not practical since there are too many quotes to type, and more critically it does not allow comments; rjson (relaxed json does), but at that point why not use yaml? 😉

**Comment by ftessier** [comment]
Scrap the idea of turning the name properties into the dictionary keys, this precludes writing a proper schema! So we should have the following, where for example `geometries` is a proper array of dictionaries for each geometry, which can then be specified in a schema:

```yaml
geometries:

  # the ion chamber spherical tip
  - name:     chamber_tip
    class:    spheres
    midpoint: [&pos 0.935, 0, -10]
    radii:    [0.05, 0.305, 0.355]
    media:
      water:  all
      air:    [1, 2, 3]
      pmma:   [4, 5]

  # the cylindrical body of the ion chamber
  - name:      chamber_body
    class:     conestack
    origin:    [*pos, 0, -10]
    direction: [-1, 0, 0]
    layers:
      - name: electrode
        thickness:    2.03
        top radii:    [0.05, 0.305, 0.355]
        bottom radii: [0.05, 0.305, 0.355]
        media:        [&medium pmma, air, *medium]
      - name: stem
        thickness:    2.0
        top radii:    0.61
        bottom radii: 0.61
        media:        *medium

  # join the chamber tip and body to build chamber
  - name:  chamber
    class: cdgeometry
    base geometry: cd_planes_for_chamber
    fill region 0: chamber_body
    fill region 1: chamber_tip
    new indexing style: true
```
